import express from "express";
import * as Job from "../controllers/JobApply.controllers.js";
import {Checktoken} from "../middleware/auth.middleware.js";
import multer from 'multer';
import storage from '../cloudinaryStorage.js';
const upload = multer({ storage });
const router = express.Router();
router.post("/send",upload.single('cv'),Job.ApplyJob);
router.get("/get",Job.GetAllApply);
router.post("/delete",Job.DeleteApply);
export default router;